# -*- coding: utf-8 -*-
"""dataset_creator.ipynb

Automatically generated by Colaboratory.

Original file is located at

## Google drive mounting
"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/content/drive')
# %cd "./path_to_project_root/"

"""## Installation of external packages"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install import-ipynb
# !pip install pydicom
# !pip install torchmetrics
#
# !pip3 install git+https://github.com/itzortzis/INBreast_XML_parser.git

"""## External and local imports"""

#import anot_core as anot
import utils.inbreast_utils as inutils
import utils.dataset_utils as dutils

paths = {
    'xml': '../INBreast/XML/',
    'dcm': '../INBreast/DICOM/',
    'csv': '../INBreast/INbreast_compact.csv',
    'dtst': './dataset/single/'
}

args = {
    'p_size': 512,
    'p_step': 50,
    'ppi': 6,  # Maximum number of malignant patches per image
    'h_ppi': 6 # Maximum number of healthy patches per image
}

l            = inutils.build_dcm_dict(paths['csv'])
non_h        = inutils.extract_mal_dcms(l)
dataset_size = dutils.create_dataset(args, paths, non_h)
